library(testthat)

# Problem 1
#
# If we list all the natural numbers below 10 that are 
# multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of 
# these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.
#

x <- seq(999)

sum(x[!(x %% 3) | !(x %% 5)]) 

answer <- 233168

# Problem 2
#
# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, find the sum of the 
# even-valued terms.
#

fib <- function(x) {
  y <- c(1, 2, 3)
  if (x < 4) {
    y <- y[1:x]
  } else {
    while (all(length(y) < x)) {
      val <- y[length(y)]+y[length(y)-1]
      y <- c(y, val)
    }
  }
  return(y)
}

x <- fib(100)[fib(100) < 4000000]
y <- sum(x[!(x %% 2)])

answer <- 4613732

# Problem 3
#
# The prime factors of 13195 are 5, 7, 13 and 29.
#
# What is the largest prime factor of the number 
# 600851475143 ?
#

val <- 600851475143
valSq <- sqrt(val)

isPrime <- function(x) {
  all(as.logical(x %% seq(2, ceiling(sqrt(x)))))
}

factors <- !(as.logical(val %% seq(valSq)))

x <- seq(valSq)[factors]

mxPrimeFac <- function(x) {
  check <- FALSE
  ln <- length(x)
  while (!check) {
    if (isPrime(x[ln])) {
      check <- TRUE
      y <- x[ln]
    }
    ln <- ln - 1
    if (ln == 0) {
      check <- TRUE
      y <- NA
    }
  }
  return(y)
}

y <- mxPrimeFac(x)

answer <- 6857

# Problem 4
#
# A palindromic number reads the same both ways. The 
# largest palindrome made from the product of two 2-digit 
# numbers is 9009 = 91 99.
#
# Find the largest palindrome made from the product of 
# two 3-digit numbers.
#


isPal <- function(x) {
  x == rev(unlist(strsplit(as.character(x), NULL)))
}


# Problem 5
#
# 2520 is the smallest number that can be divided by each 
# of the numbers from 1 to 10 without any remainder.
#
# What is the smallest positive number that is evenly 
# divisible by all of the numbers from 1 to 20?

library(compiler)

p5 <- function(x) {
  if (!(x %% 2)) {
    y <- x
  } else {
    y <- x * 2
  }
  val <- y
  sq <- seq(x)
  while (sum(val %% sq)) {
    val <- val + y
  }
  return(val)
}

cp5 <- cmpfun(p5)

y <- cp5(20)

answer <- 232792560

# Problem 6
#
# The sum of the squares of the first ten natural numbers is,
#
# 1^2 + 2^2 + ... + 10^2 = 385
# The square of the sum of the first ten natural numbers is,
#
# (1 + 2 + ... + 10)^2 = 55^2 = 3025
# Hence the difference between the sum of the squares of 
# the first ten natural numbers and the square of the sum 
# is 3025 - 385 = 2640.
#
# Find the difference between the sum of the squares of the 
# first one hundred natural numbers and the square of the sum.
#
#

sqDiff <- function(x) {
  sum(seq(x))^2 - sum(seq(x)^2)
}

y <- sqDiff(100)

answer <- 25164150


# Problem 7
# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, 
# we can see that the 6th prime is 13.
#
# What is the 10 001st prime number?
#

# isPrime2 seems faster than isPrime
# need to check more in depth
isPrime2 <- function(x) {
  !(sum(!(x %% seq(2, ceiling(sqrt(x))))))
}


nthPrime <- function(x) {
  val <- 2
  ln <- 1
  while (ln < x) {
    val <- val + 1
    if (isPrime2(val)) {
      ln <- ln + 1
    }
  }
  return(val)
}

y <- nthPrime(10001)

answer <- 104743


# Problem 8
# 
# Find the greatest product of five consecutive digits in the 1000-digit number.
#
# 73167176531330624919225119674426574742355349194934
# 96983520312774506326239578318016984801869478851843
# 85861560789112949495459501737958331952853208805511
# 12540698747158523863050715693290963295227443043557
# 66896648950445244523161731856403098711121722383113
# 62229893423380308135336276614282806444486645238749
# 30358907296290491560440772390713810515859307960866
# 70172427121883998797908792274921901699720888093776
# 65727333001053367881220235421809751254540594752243
# 52584907711670556013604839586446706324415722155397
# 53697817977846174064955149290862569321978468622482
# 83972241375657056057490261407972968652414535100474
# 82166370484403199890008895243450658541227588666881
# 16427171479924442928230863465674813919123162824586
# 17866458359124566529476545682848912883142607690042
# 24219022671055626321111109370544217506941658960408
# 07198403850962455444362981230987879927244284909188
# 84580156166097919133875499200524063689912560717606
# 05886116467109405077541002256983155200055935729725
# 71636269561882670428252483600823257530420752963450

x <- '7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450'

ll <- c()
for (i in 1:995){
  x1 <- as.numeric(substr(x, i, i)) 
  x2 <- as.numeric(substr(x, i+1, i+1))
  x3 <- as.numeric(substr(x, i+2, i+2))
  x4 <- as.numeric(substr(x, i+3, i+3))
  x5 <- as.numeric(substr(x, i+4, i+4))
  ll <- c(ll, (x1*x2*x3*x4*x5))
}
y <- max(ll)

answer <- 40824



# Problem 15
# Starting in the top left corner of a 22 grid, there are 
# 6 routes (without backtracking) to the bottom right corner.
#
# How many routes are there through a 2020 grid?
#