# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs <- function(N, thin) {
    .Call('chRonos_gibbs', PACKAGE = 'chRonos', N, thin)
}

rcpp_hello_world <- function() {
    .Call('chRonos_rcpp_hello_world', PACKAGE = 'chRonos')
}

